/**
 * MyFeatures
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskTemplateDto } from './taskTemplateDto';


export interface TaskOccurrenceDto { 
    id?: number;
    taskTemplateId?: number;
    committedDate?: string | null;
    dueDate?: string | null;
    description?: string | null;
    completionDate?: string | null;
    taskTemplate?: TaskTemplateDto;
}

