/**
 * MyFeatures
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IntervalType } from './intervalType';


export interface TaskTemplateDto { 
    id?: number;
    description?: string | null;
    recurring?: boolean;
    renewOnDueDate?: boolean | null;
    intervalValue?: number | null;
    intervalType?: IntervalType;
    rowIndex?: number | null;
}
export namespace TaskTemplateDto {
}


