// <auto-generated />
using System;
using Infrastructure.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MyFeaturesDbContext))]
    [Migration("20260321171710_RenameTaskSchema")]
    partial class RenameTaskSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Entities.Notepad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RowIndex")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notepads");
                });

            modelBuilder.Entity("Infrastructure.Entities.TaskOccurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CommittedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommittedDate")
                        .HasDatabaseName("IDX_CommittedDate");

                    b.HasIndex("CompletionDate")
                        .HasDatabaseName("IDX_CompletionDate")
                        .HasFilter("CompletionDate IS NOT NULL");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("IDX_DueDate");

                    b.HasIndex("TaskTemplateId")
                        .HasDatabaseName("IDX_TaskTemplateID");

                    b.ToTable("TaskOccurrences", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.TaskTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IntervalType")
                        .HasColumnType("int");

                    b.Property<int?>("IntervalValue")
                        .HasColumnType("int");

                    b.Property<bool>("Recurring")
                        .HasColumnType("bit");

                    b.Property<bool?>("RenewOnDueDate")
                        .HasColumnType("bit");

                    b.Property<int?>("RowIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TaskTemplates", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.TaskOccurrence", b =>
                {
                    b.HasOne("Infrastructure.Entities.TaskTemplate", "TaskTemplate")
                        .WithMany("TaskOccurrences")
                        .HasForeignKey("TaskTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskTemplate");
                });

            modelBuilder.Entity("Infrastructure.Entities.TaskTemplate", b =>
                {
                    b.Navigation("TaskOccurrences");
                });
#pragma warning restore 612, 618
        }
    }
}
